Digital_Graphics/Digital_Graphics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Digital_Graphics/core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.home, name='index'),
    path('courses/', views.courses, name='courses'),
    path('course-detail/?=<slug:slug>/',
         views.single_course, name='course-detail'),

    path('send-message/', views.contact, name='send-message'),
]

Digital_Graphics/core/models.py
from django.db import models
from django.utils.text import slugify


class teachers(models.Model):
    image = models.ImageField(upload_to='medaifiles', blank=True, null=True)
    name = models.CharField(max_length=20)
    profession = models.CharField(max_length=20, default='Graphic Designer')

    instagram = models.URLField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    linkdin = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name + self.profession


class course(models.Model):
    name = models.CharField(max_length=50)

    image = models.ImageField(upload_to='mediafiles', blank=True, null=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    info = models.TextField()
    fee = models.FloatField(default=1000)
    duration = models.CharField(
        max_length=10, help_text='like 3 months or 12 months')
    created_date = models.DateField()
    last_date = models.DateField()

    total_seats = models.PositiveIntegerField(default=30)
    seats_reserved = models.PositiveIntegerField(
        null=True, blank=True, default=0)
    seats_remaining = models.PositiveIntegerField(
        null=True, blank=True)

    is_activated = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        super(course, self).save(*args, **kwargs)


class message(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    msg = models.TextField()

    def __str__(self):
        return self.name

Digital_Graphics/core/views.py
from django.shortcuts import redirect, render
from django.utils import timezone
from .models import course, teachers, message

# Create your views here.

today = timezone.now()


def home(request):
    teacher = teachers.objects.all()

    context = {
        'teachers': teacher
    }
    return render(request, 'index.html', context)


def courses(request):
    all_courses = course.objects.filter(is_activated=True, last_date__gt=today)

    context = {
        'courses': all_courses,
    }
    return render(request, 'courses.html', context)


def single_course(request, slug):
    get_course = course.objects.get(slug=slug)

    context = {
        'course': get_course,
    }
    return render(request, 'single_course.html', context)


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        msg = request.POST.get('msg')

        new_message = message(
            name=name,
            email=email,
            msg=msg
        )
        new_message.save()

        return redirect('core:index')

Digital_Graphics/templates/courses.html
{% load static %}


<!DOCTYPE html>
<!-- upto 2 directory depth-->
<html lang="en-US">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Digital Graphic Designing</title>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin" />
  <link rel="preload" as="style"
    href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;700;800&amp;display=swap" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;700;800&amp;display=swap" media="print"
    onload="this.media='all'" />
  <noscript>
    <link rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;700;800&amp;display=swap" />
  </noscript>
  <link href="{% static 'css/font-awesome/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/aos.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">





  <noscript>
    <style type="text/css">
      [data-aos] {
        opacity: 1 !important;
        transform: translate(0) scale(1) !important;
      }
    </style>
  </noscript>
</head>

<body id="top">
  <header class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="header-nav" role="navigation">
      <div class="container"><a class="link-dark navbar-brand site-title mb-0" href="{% url 'core:index' %}">Digital
          Graphic Designing</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto me-2">
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}#about">About</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}#services">Courses</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}#team">Team</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}#contact">Contact</a></li>
          </ul><a class="btn btn-primary" href="{% url 'core:index' %}">Get Started</a>
        </div>
      </div>
    </nav>
  </header>






  <!-- ========================================== -->
  <!-- COURSES -->
  <!-- ========================================== -->
  <div class="section pt-5 pb-3 py-lg-5 px-2 px-lg-4" id="team">
    <div class="container">
      <div class="text-center mb-5">
        <h2 class="marker marker-center change">All Courses</h2>
      </div>
    </div>
    <div class="carousel carousel-dark slide pb-3" id="carouselTeam" data-bs-ride="carousel" data-aos="zoom-in-up">
      <div class="container-narrow">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="6000">
            <div class="row">

              <!-- Logic -->
              {% for course in courses %}
              <div class="col-md-4">
                <div class="card d-block mb-3">
                  {% if course.image %}
                  <img class="card-img-top" src="{{ course.image.url }}" alt="image" />
                  {% else %}
                  <img class="card-img-top" src="{% static 'images/portfolio/1.jpg' %}" alt="image" />
                  {% endif %}


                  <div class="card-body text-center">
                    <div class="h5 mb-1">{{ course.name }}</div>
                    <div class="nav text-light justify-content-center">
                      <a href="{% url 'core:course-detail' course.slug %}" class="link btn-primary btn">
                        Learn more <span><i class="fas fa-arrow-right"></i></span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              {% empty %}
              <div class="container center">
                <p class="text-danger text-center h1"><strong>No Courses Avaiable</strong> <br>
                  <a href="{% url 'core:index' %}" class="btn btn-primary">Go back</a>
                </p>

              </div>
              {% endfor %}

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>







  <!-- ================================= -->
  <!-- FOOTER -->
  <!-- ================================= -->

  <footer class="py-5 px-2 bg-light" id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-12 mb-3">
          <div class="mb-3">
            <div class="h4">Digital Graphic Designing</div>
            <p class="text-muted">Your <b>Success</b> is our <b>mission</b>
            </p>
            <div class="social-nav">
              <nav role="navigation">
                <ul class="nav text-light">
                  <li class="nav-item"><a class="nav-link" href="https://twitter.com/templateflip" title="Twitter"><i
                        class="fab fa-twitter"></i><span class="menu-title sr-only">Twitter</span></a></li>
                  <li class="nav-item"><a class="nav-link" href="https://www.facebook.com/templateflip"
                      title="Facebook"><i class="fab fa-facebook"></i><span
                        class="menu-title sr-only">Facebook</span></a></li>
                  <li class="nav-item"><a class="nav-link" href="https://www.instagram.com/templateflip"
                      title="Instagram"><i class="fab fa-instagram"></i><span
                        class="menu-title sr-only">Instagram</span></a></li>
                  <li class="nav-item"><a class="nav-link" href="https://www.linkedin.com/" title="LinkedIn"><i
                        class="fab fa-linkedin"></i><span class="menu-title sr-only">LinkedIn</span></a></li>
                  <li class="nav-item"><a class="nav-link" href="https://www.behance.net/templateflip"
                      title="Behance"><i class="fab fa-behance"></i><span class="menu-title sr-only">Behance</span></a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="text-small text-muted">
            <div class="mb-1">&copy; Copyright <strong>Digital Graphic Designing</strong>. All rights reserved.
            </div>
            <div>
              <!-- Make sure to buy a license for the template before removing the line below. Buy license on https://templateflip.com/ -->Design
              by Kashif with the help of <a href="https://templateflip.com/" target="_blank">TemplateFlip</a>
            </div>
          </div>
        </div>
        <div class="col-lg-2 col-md-6 mb-3">
          <div class="text-uppercase mb-2">Courses</div>
          <div class="nav flex-column">
            <a class="nav-link px-0" href="{% url 'core:courses' %}">Graphic Design</a>
            <a class="nav-link px-0" href="{% url 'core:courses' %}">Web Design</a>
            <a class="nav-link px-0" href="{% url 'core:courses' %}">UI/UX Design</a>
          </div>
        </div>
        <div class="col-lg-2 col-md-6 mb-3">
          <div class="text-uppercase mb-2">About</div>
          <div class="nav flex-column">
            <a class="nav-link px-0" href="#about">About</a>
            <a class="nav-link px-0" href="#contact">Contact</a>
            <a class="nav-link px-0" href="#about">Terms</a>
          </div>
        </div>
        <div class="col-lg-2 col-md-6 mb-3">
          <div class="text-uppercase mb-2">Contact Us</div>
          <div class="text-small">
            <div class="mb-1"><strong>Phone:</strong><br />+966-57-093-9804</div>
            <div class="mb-1"><strong>Email:</strong><br />bh6735971@gmail.com</div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  </div>
  </div>
  <div id="scrolltop"><a class="btn btn-secondary" href="#top"><span class="icon"><i
          class="fas fa-angle-up fa-x"></i></span></a></div>
  <script src="{% static 'scripts/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'scripts/masonry.pkgd.min.js' %}"></script>
  <script src="{% static 'scripts/BigPicture.min.js' %}"></script>
  <script src="{% static 'scripts/purecounter.min.js' %}"></script>
  <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'scripts/aos.min.js' %}"></script>
  <script src="{% static 'scripts/main.js' %}"></script>
</body>



</html>

Digital_Graphics/templates/single_course.html
{% load static %}
{% load mathfilters %}

<!DOCTYPE html>
<!-- upto 2 directory depth-->
<html lang="en-US">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Digital Graphic Designing</title>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin" />
  <link rel="preload" as="style"
    href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;700;800&amp;display=swap" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;700;800&amp;display=swap" media="print"
    onload="this.media='all'" />
  <noscript>
    <link rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;700;800&amp;display=swap" />
  </noscript>
  <link href="{% static 'css/font-awesome/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/aos.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">





  <noscript>
    <style type="text/css">
      [data-aos] {
        opacity: 1 !important;
        transform: translate(0) scale(1) !important;
      }
    </style>
  </noscript>
</head>

<body id="top">
  <header class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="header-nav" role="navigation">
      <div class="container"><a class="link-dark navbar-brand site-title mb-0" href="{% url 'core:index' %}">Digital
          Graphic Designing</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto me-2">
            <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}#about">About</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}#services">Courses</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}#team">Team</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}#contact">Contact</a></li>
          </ul><a class="btn btn-primary" href="{% url 'core:courses' %}">Get Started</a>
        </div>
      </div>
    </nav>
  </header>
  <div class="page-content">
    <div id="content">


      <div class="section pt-3 pt-lg-5 px-2 px-lg-4" id="about">

        <div class="container">
          <div class="row py-3 py-lg-5">
            <div class="col-lg-6 col-md-5 px-3" data-aos="fade-zoom-in" data-aos-delay="50"
              data-aos-easing="ease-in-back">
              {% if course.image %}
              <img class="card-img-top" src="{{ course.image.url }}" alt="image" />
              {% else %}
              <img class="card-img-top" src="{% static 'images/portfolio/1.jpg' %}" alt="image" />
              {% endif %}


            </div>
            <div class=" mt-3 col-lg-6 col-md-7 px-2" data-aos="zoom-in" data-aos-delay="100">
              <div class="h3 mb-2"><strong>{{ course.name }}</strong> </div>
              <p class="text-secondary mb-2">{{ course.info }}</p>
              <div>

                <!-- Duration -->
                <div class="py-1">
                  <div style="width: 60%" class="d-flex text-small fw-bolder"><span class="text-muted"
                      style="width: 60%;">Duration</span><span style="width: 30%;" class="">
                      {{ course.duration }}
                    </span>
                  </div>
                </div>

                <div class="py-1">
                  <div style="width: 60%" class="d-flex text-small fw-bolder"><span class="text-muted"
                      style="width: 60%;">Seats Remaining</span><span style="width: 30%;" class="">
                      {{ course.total_seats | sub:course.seats_reserved }}
                    </span>
                  </div>
                </div>
                <div class="py-1">
                  <div style="width: 60%" class="d-flex text-small fw-bolder"><span class="text-muted"
                      style="width: 60%;">Seats Reserved</span><span style="width: 30%;" class="">
                      {{ course.seats_reserved }}
                    </span>
                  </div>
                </div>

                <div class="py-1">
                  <div style="width: 60%" class="d-flex text-small fw-bolder"><span class="text-muted"
                      style="width: 60%;">Fee</span><span style="width: 30%;" class="">{{ course.fee }} PKR</span>
                  </div>
                </div>

                <div class="py-1">
                  <div style="width: 60%" class="d-flex text-small fw-bolder"><span class="text-muted"
                      style="width: 60%;">Last Date</span><span style="width: 30%;" class="">
                      {{ course.last_date }}</span>
                  </div>
                </div>

                <div class="mt-5">

                  <p>To reserve your seat call <a href="tel:+966570939804">+966 57 093 9804</a> now</p>

                  <a href="tel:+966570939804" class="btn btn-primary">Reserve Seat Now</a>

                </div>


              </div>
            </div>
          </div>

        </div>
      </div>




      <!-- ================================ -->
      <!-- TESTIMONIALS -->
      <!-- ================================ -->
      <!-- <div class="section py-3 py-lg-5 px-2 px-lg-4" id="testimonials">
        <div class="container-narrow">
          <div class="text-center mb-5">
            <h2 class="marker marker-center">Client Testimonials</h2>
          </div>
          <div class="row">
            <div class="col-md-6 mb-5" data-aos="fade-right" data-aos-delay="100">
              <div class="d-flex ms-md-3"><span><i class="fas fa-2x fa-quote-left"></i></span><span class="m-2">Bring to
                  the table win-win survival strategies to ensure proactive domination. User generated content in
                  real-time will have multiple touchpoints for offshoring.</span></div>
              <div class="d-flex justify-content-end align-items-end">
                <div class="text-end me-2">
                  <div class="fw-bolder">Aiyana</div>
                  <div class="text-small">CEO / Specely</div>
                </div><img class="me-md-3 rounded" src="{% static 'images/testimonials/client1.jpg' %}" width="96"
                  height="96" alt="client 1" />
              </div>
            </div>
            <div class="col-md-6 mb-5" data-aos="fade-left" data-aos-delay="300">
              <div class="d-flex ms-md-3"><span><i class="fas fa-2x fa-quote-left"></i></span><span
                  class="m-2">Capitalize on low hanging fruit to identify a ballpark value added activity to beta test.
                  Organically grow the holistic world view of disruptive innovation.</span></div>
              <div class="d-flex justify-content-end align-items-end">
                <div class="text-end me-2">
                  <div class="fw-bolder">Alexander</div>
                  <div class="text-small">CEO / Combtree</div>
                </div><img class="me-md-3 rounded" src="{% static 'images/testimonials/client2.jpg' %}" width="96"
                  height="96" alt="client 1" />
              </div>
            </div>
            <div class="col-md-6 mb-5" data-aos="fade-right" data-aos-delay="100">
              <div class="d-flex ms-md-3"><span><i class="fas fa-2x fa-quote-left"></i></span><span
                  class="m-2">Podcasting operational change management inside of workflows to establish a framework.
                  Taking seamless key performance indicators offline to maximise potential.</span></div>
              <div class="d-flex justify-content-end align-items-end">
                <div class="text-end me-2">
                  <div class="fw-bolder">Ariya</div>
                  <div class="text-small">CTO / Softone</div>
                </div><img class="me-md-3 rounded" src="{% static 'images/testimonials/client3.jpg' %}" width="96"
                  height="96" alt="client 1" />
              </div>
            </div>
            <div class="col-md-6 mb-5" data-aos="fade-left" data-aos-delay="300">
              <div class="d-flex ms-md-3"><span><i class="fas fa-2x fa-quote-left"></i></span><span
                  class="m-2">Collaboratively administrate empowered markets via plug-and-play networks. Dynamically
                  procrastinate B2C users after installed base benefits.</span></div>
              <div class="d-flex justify-content-end align-items-end">
                <div class="text-end me-2">
                  <div class="fw-bolder">Braiden</div>
                  <div class="text-small">CFO / Markoo</div>
                </div><img class="me-md-3 rounded" src="{% static 'images/testimonials/client4.jpg' %}" width="96"
                  height="96" alt="client 1" />
              </div>
            </div>
          </div>
        </div>
      </div> -->




      <!-- ================================= -->
      <!-- FOOTER -->
      <!-- ================================= -->

      <footer class="py-5 px-2 bg-light" id="footer">
        <div class="container">
          <div class="row">
            <div class="col-lg-4 col-md-12 mb-3">
              <div class="mb-3">
                <div class="h4">Digital Graphic Designing</div>
                <p class="text-muted">Your <b>Success</b> is our <b>mission</b>
                </p>
                <div class="social-nav">
                  <nav role="navigation">
                    <ul class="nav text-light">
                      <li class="nav-item"><a class="nav-link" href="https://twitter.com/" title="Twitter"><i
                            class="fab fa-twitter"></i><span class="menu-title sr-only">Twitter</span></a></li>
                      <li class="nav-item"><a class="nav-link" href="https://www.facebook.com/" title="Facebook"><i
                            class="fab fa-facebook"></i><span class="menu-title sr-only">Facebook</span></a></li>
                      <li class="nav-item"><a class="nav-link" href="https://www.instagram.com/" title="Instagram"><i
                            class="fab fa-instagram"></i><span class="menu-title sr-only">Instagram</span></a></li>
                      <li class="nav-item"><a class="nav-link" href="https://www.linkedin.com/" title="LinkedIn"><i
                            class="fab fa-linkedin"></i><span class="menu-title sr-only">LinkedIn</span></a></li>
                      <li class="nav-item"><a class="nav-link" href="https://www.behance.net/" title="Behance"><i
                            class="fab fa-behance"></i><span class="menu-title sr-only">Behance</span></a></li>
                    </ul>
                  </nav>
                </div>
              </div>
              <div class="text-small text-muted">
                <div class="mb-1">&copy; Copyright <strong>Digital Graphic Designing</strong>. All rights reserved.
                </div>
                <div>
                  <!-- Make sure to buy a license for the template before removing the line below. Buy license on https://templateflip.com/ -->Design
                  by Kashif with the help of <a href="https://templateflip.com/" target="_blank">TemplateFlip</a>
                </div>
              </div>
            </div>
            <div class="col-lg-2 col-md-6 mb-3">
              <div class="text-uppercase mb-2">Courses</div>
              <div class="nav flex-column">
                <a class="nav-link px-0" href="{% url 'core:courses' %}">Graphic Design</a>
                <a class="nav-link px-0" href="{% url 'core:courses' %}">Web Design</a>
                <a class="nav-link px-0" href="{% url 'core:courses' %}">UI/UX Design</a>
              </div>
            </div>
            <div class="col-lg-2 col-md-6 mb-3">
              <div class="text-uppercase mb-2">About</div>
              <div class="nav flex-column">
                <a class="nav-link px-0" href="{% url 'core:index' %}#about">About</a>
                <a class="nav-link px-0" href="{% url 'core:index' %}#contact">Contact</a>
                <a class="nav-link px-0" href="{% url 'core:index' %}#about">Terms</a>
              </div>
            </div>
            <div class="col-lg-2 col-md-6 mb-3">
              <div class="text-uppercase mb-2">Contact Us</div>
              <div class="text-small">
                <div class="mb-1"><strong>Phone:</strong><br />+966-57-093-9804</div>
                <div class="mb-1"><strong>Email:</strong><br />bh6735971@gmail.com</div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <div id="scrolltop"><a class="btn btn-secondary" href="#top"><span class="icon"><i
          class="fas fa-angle-up fa-x"></i></span></a></div>
  <script src="{% static 'scripts/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'scripts/masonry.pkgd.min.js' %}"></script>
  <script src="{% static 'scripts/BigPicture.min.js' %}"></script>
  <script src="{% static 'scripts/purecounter.min.js' %}"></script>
  <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'scripts/aos.min.js' %}"></script>
  <script src="{% static 'scripts/main.js' %}"></script>
</body>

</html>